Додади чести грешки од Википедија
skopjehacklab/sentence-collector pull request #16
Opened 2020-04-09 22:10 UTC by MatejMecka

2020-04-09 22:11 UTC, MatejMecka commented on dictionary.json
> +    "ХонгКонг":"Хонгконг",
```suggestion
    "ХонгКонг":"Хонг конг",
```

2020-04-09 22:11 UTC, MatejMecka commented on dictionary.json
> +    "ЛосАнѓелес":"ЛосАнџелес",
```suggestion
    "ЛосАнѓелес":"Лос Анџелес",
```

2020-04-09 22:12 UTC, MatejMecka commented on dictionary.json
> +    "датабаза":"базанаподатоци",
```suggestion
    "датабаза":"база на податоци",
```

2020-04-09 22:12 UTC, MatejMecka commented on dictionary.json
> +    "датабазата":"базатанаподатоци",
```suggestion
    "датабазата":"базата на податоци",
```

2020-04-09 22:28 UTC, lubeskih commented on dictionary.json
> +    "ХонгКонг":"Хонгконг",
Outdated сугестии не можат да се комитираат.

2020-04-09 22:31 UTC, lubeskih requested changes
Остаив неколку коментари, плис стави спејс меѓу клучот и вредноста.

`"незнам": "не знам"`, а не `"незнам":"не знам"`

2020-04-09 22:31 UTC, lubeskih commented on dictionary.json
> +        "ревзема":"резема",
?

2020-04-09 22:31 UTC, lubeskih commented on dictionary.json
> +        "оддржу":"одржу",
не знам шо е ова

2020-04-09 22:31 UTC, lubeskih commented on dictionary.json
> +        "ЊуЈорк":"Њујорк",
Овие не ги заборавај со градовиве

2020-04-09 22:31 UTC, lubeskih commented on dictionary.json
> +        "јалистата":"госписокот",
?

2020-04-09 22:31 UTC, lubeskih commented on dictionary.json
> +        "Спецификации":"Карактеристики",
со мали букви нека бидат сите

2020-04-10 06:36 UTC, gocemitevski commented on dictionary.json
> +        "ревзема":"резема",
Веројатно `превзема:презема`

2020-04-10 06:39 UTC, gocemitevski commented on dictionary.json
> +        "оддржу":"одржу",
`"оддржу":"одржи"`?

2020-04-10 06:42 UTC, gocemitevski commented on dictionary.json
> +        "јалистата":"госписокот",
Листа е исто македонски збор. Не гледам зошто би го поправале.

Што правиме ако `Листи` и Списоци ако се на почеток на реченицата?

Интернационални е различно од меѓународни. И тоа мислам дека не траба да се менува.

2020-04-10 06:43 UTC, gocemitevski commented on dictionary.json
> +        "Спецификации":"Карактеристики",
Маскиран е различно од обележан. И маскиран е македонски збор.

2020-04-10 06:44 UTC, gocemitevski approved these changes
Оставив коментари на повеќе места. Мислам дека некаде правиме непотребни или погрешни поправки.

2020-04-10 06:46 UTC, gocemitevski requested changes
Порешно направив „Approve“ претходно.

2020-04-10 09:19 UTC, MatejMecka commented on dictionary.json
> +        "ревзема":"резема",
`("ревзема", "резема", "превзема... -> презема...", "*Промена на зборови од типот '''превзема...''' во '''презема...''', без ''в'', синтаксна грешка."),`

2020-04-10 09:19 UTC, MatejMecka commented on dictionary.json
> +        "ревзема":"резема",
```suggestion
        "превзема":"презема",
```

2020-04-10 09:20 UTC, MatejMecka commented on dictionary.json
> +        "оддржу":"одржу",
`(" оддржу", " одржу", "оддржу... -> одржу...", "*Промена на зборови од типот ''' оддржу...''' во ''' одржу...''', само со едно ''д'', синтаксна грешка."),`

2020-04-10 09:21 UTC, MatejMecka commented on dictionary.json
> +        "ЊуЈорк":"Њујорк",
```suggestion
        "Њу Јорк":"Њујорк",
```

2020-04-10 09:21 UTC, MatejMecka commented on dictionary.json
> +        "ЛосАнѓелес":"ЛосАнџелес",
```suggestion
        "Лос Анѓелес":"Лос Анџелес",
```

2020-04-10 09:22 UTC, MatejMecka commented on dictionary.json
> +        "ХонгКонг":"Хонгконг",
```suggestion
        "Хонг Конг":"Хонг конг",
```

2020-04-10 12:10 UTC, MatejMecka commented on dictionary.json
> +        "датабаза": "базанаподатоци",
```suggestion
        "датабаза": "база на податоци",
```

2020-04-10 12:10 UTC, MatejMecka commented on dictionary.json
> +        "датабазата": "базатанаподатоци",
```suggestion
        "датабазата": "базата на податоци",
```

2020-04-10 12:26 UTC, gocemitevski commented on dictionary.json
> +        "оддржу":"одржу",
Ок, јасно. Ок ми изгледа ако е така.

2020-04-10 12:28 UTC, gocemitevski commented on dictionary.json
> +        "Спецификации":"Карактеристики",
@MatejMecka моја грешка. Маркиран е обележан, да. Добро е како што го имаш направено.

2020-04-10 20:23 UTC, lubeskih approved these changes
:+1:

2020-04-10 20:23 UTC, merged